server:
  port: 8081
  servlet:
    context-path: /tagPrc
  connection-timeout: 5000

spring :

  # mysql
  mysql:
   datasource:
     url: dbc:mysql://localhost:3306/ease-run?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

  redis:
    #地址
    host: localhost
    #端口
    port: 6379
    #索引库
    database: 1
    #密码
    password:
    #超时时间
    timeout: 5000ms
    # 连接池设置
    pool:
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
    #其他配置
# spring boot 简单配置日志
logging:
  path: C:\workspace\logs\tagPrc
  #level.com.chakid.logging : trace
  # 指定文件中日志输出的格式
  pattern.file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
  # 指定日志配置文件
  file: C:\workspace\logs\tagPrc\tagPrc.log

swagger2:
  ebable: true
  version: v1.0
  name: api
  email: 506937617@qq.com
  title: API验证
  description: 接口文档
  path: com.prc_springboot.mst.contoller
